---

root: true
parser: '@typescript-eslint/parser'
extends:
  - plugin:@next/next/recommended
  - '@mklp/eslint-config/react'

settings:
  import/extensions: &extensions
    - .js
    - .jsx
    - .ts
    - .tsx
  import/resolver:
    node:
      extensions: *extensions

plugins:
  - '@typescript-eslint'

rules:
  import/extensions:
    - error
    - never
    - json: always

  react/function-component-definition:
    - warn
    - namedComponents: arrow-function
      unnamedComponents: arrow-function

  react/jsx-filename-extension:
    - error
    - extensions:
        - jsx
        - tsx
