
---

root: true
parser: '@typescript-eslint/parser'
extends:
  - plugin:@next/next/recommended
  - '@mklp/eslint-config/react'
  - prettier

settings:
  import/extensions: &extensions
    - .js
    - .jsx
    - .ts
    - .tsx
  import/resolver:
    node:
      extensions: *extensions

plugins:
  - '@typescript-eslint'

rules:
  class-methods-use-this: off
  react/require-default-props: off

  import/extensions:
    - error
    - never
    - json: always

  react/function-component-definition:
    - warn
    - namedComponents: arrow-function
      unnamedComponents: arrow-function

  react/jsx-filename-extension:
    - error
    - extensions:
        - jsx
        - tsx

overrides:
  - files:
      - "*.ts"
      - "*.tsx"
    rules:
      no-undef: off

  - files: '*.stories.*'
    rules:
      import/no-extraneous-dependencies:
        - error
        - devDependencies: true
  - files:
      - jest.setup.js
      - '*.test.*'
    plugins:
      - jest
    extends:
      - plugin:jest/recommended
    env:
      jest/globals: true
